### ISSUE TITLE
Question about the resource for this project

### ISSUE THREAD

**Issue by NinjaCXX** [martius-lab/videosaur#1]
Thanks for your great work. I have two questions:
1. How much hard disk is required for all data sets?
2. How long do you need for training?

Thanks very much.

**Comment by NinjaCXX** [comment]
Could you please answer my question? @zadaianchuk

**Comment by zadaianchuk** [comment]
Sorry, I thought it is not relevant anymore as is was long time ago. 

For the datasets, if I remember correctly should be not more than 200GB, for example move-c after preprocessing is 12GB

The question that you are asking highly depends on exact hardware, on A100 one run with small DINO is taking less than 24 hours, something like 20. 
Given that we have all the configurations and datasets released you can easily get more details yourself. Hope that helps.

**Comment by Eaphan** [comment]
Thanks for your valuable suggestion.

**Comment by NinjaCXX** [comment]
Thanks for your valuable feedback.
