### ISSUE TITLE
Question on the backbone

### ISSUE THREAD

**Issue by MLDeS** [martius-lab/videosaur#2]
Hi All,

Thanks for the wonderful work!

I just wanted to confirm one thing. Are the results (Table 1) shown based on when the ViT backbone is frozen throughout the training? And only the subsequent slot decoders are updated?

Thanks!

**Comment by mseitzer** [comment]
Hi, 

thanks for the question! Yes, you are correct. In all experiments in the paper, the ViT remains frozen during training. 

Let us know if you have more questions.
