### ISSUE TITLE
About DINOSAUR

### ISSUE THREAD

**Issue by SydCS** [martius-lab/videosaur#3]
I wonder how to use the configuration for the DINOSAUR model to train/test a DINOSAUR. Could you offer me some instructions? A million thanks!

**Comment by zadaianchuk** [comment]
Should be as simple as 
1. Prepare dataset (for example COCO dataset, see: https://github.com/martius-lab/videosaur/blob/main/data/save_coco.py)
2. Run training:
`poetry run python -m videosaur.train  configs/dinosaur/coco_base14_dinov2.yml`
