### ISSUE TITLE
Mask output

### ISSUE THREAD

**Issue by MLDeS** [martius-lab/videosaur#4]
Hello and congrats again on the very nice work.

I wanted to confirm another thing. The final masks that we see for, e.g., on Figure 4, how are they generated? Is it per slot decoded directly from the slot decoder, meaning, there is not even indirect propagation of gradient through the reconstruction loss? Like, it is a completely independent branch of conv2d that broadcasts the decoded slots to 2d spatial masks? While the other branch produce the patch feature reconstruction and probabilities to produce the learning signals?

Thanks a lot!

**Comment by zadaianchuk** [comment]
The masks outputs are produces by the decoder, i.e. for Mixer Decoder see 
https://github.com/martius-lab/videosaur/blob/00c506a46570e609c4b2bcd11ffe89335a7b1cd8/videosaur/modules/decoders.py#L227 

What do you mean by " indirect propagation of gradient"? During evaluation everything is frozen and masks are output of the decoder conditioned on slots encodings. Hope this helps.

**Comment by MLDeS** [comment]
Thanks, I understood this part, that the masks are produced by the slot decoder. What I meant by "indirect propagation of gradient" is something like what the first slot attention paper does. The masks are produced as a 4th channel and the reconstruction loss is calculated on the combined image. In your case, this may not be the case since you are reconstructing the patch features and not the image. Therefore, what I asked is if the slot decoded masks are completely an independent branch which is only like a spatial broadcast of the slots without any gradient updates on that branch since there is no direct supervision on the masks. Is this the case?

**Comment by zadaianchuk** [comment]
In DINOSAUR and VideoSAUR the process is similar to SA, as those methods are predicting features by combining features using predicted attention masks. So in this regard we indeed have gradient propagation though masks
