### ISSUE TITLE
Long training time 

### ISSUE THREAD

**Issue by alexcbb** [martius-lab/videosaur#5]
Hello,

First of all thank you for your really great job on this project.
I was trying to launch the experiments in order to replicate the results on Movi-C but it seems that the training time is really longer to what is announced in the paper for me : one full training of 100k steps on one A100 gpu takes roughly 80hours with vit_small_dino backbone (vs the 18h announced). Did you do any features pre-extraction to obtain this efficiency or do you perform inference "on the fly" while training the model ? 

I double checked the libraries version and everything fits correctly on my side, as well as the hyperparameters.

Thank you in advance !

**Comment by zadaianchuk** [comment]
Hi! Thanks for your interested in our paper! 
I'm not sure what is exactly problems with the efficiency of the training. 

Just to confirm: are you using optimizations (see https://github.com/martius-lab/videosaur/blob/5d09311ba862898eedf28976990ce0a012ac69b7/videosaur/train.py#L38C1-L40C2)?

Also what do you mean by the "on the fly"?

**Comment by alexcbb** [comment]
Hi, by using the optimizations the training go accelerated by almost x2 (so ~ 40h for the full training) but it still longer than 20h. 
By "on the fly", I mean that you always perform a forward through the DINO backbone model at each training iteration. Wouldn't it be faster to just pre-extract all the DINO features as the model is frozen during the training process of VIDEOSAUR ? As the DINO inference time might be the bottleneck maybe it would allow a faster training ? 

In parallel, I tried to simplify the implementation in a repo of mine and with the latest version of lightning and it seems that I'm able to perform the training at 1.85 it/s (VS 0.60it/s in the original implementation so an acceleration of almost x3 !). I'm not sure what might be the issue here, but it seems that something make the training slow here.

Thank you again for your answers !

**Comment by zadaianchuk** [comment]
> Wouldn't it be faster to just pre-extract all the DINO features as the model is frozen during the training process of VIDEOSAUR ? As the DINO inference time might be the bottleneck maybe it would allow a faster training ?

It depends if you still what to use augmentations or not, as those are better to apply on original image. 
I think bottlebeck is decoder actually (depends on its size and is not what much for Mixer but for MLP decoder it is a largly decoder).
