### ISSUE TITLE
Weighting loss, typo in the paper ?

### ISSUE THREAD

**Issue by alexcbb** [martius-lab/videosaur#6]
Hello,

In the paper it is mentioned that a weighting value of 0.1 is applied to the feature reconstruction loss for real-world experiments but by looking in the config files and the code it's the reverse that is done : weight of 0.1 for timesim and 1.0 for feature reconstruction. Is it a typo in the paper ? thank you in advance for the clarifications

**Comment by zadaianchuk** [comment]
Yes, I think you are right, paper should say: 0.1 for timesim.
